//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAula4_SantiagoVieira_JohnSebastianVillegas
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IntegranteEquipo
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        [Display(Name = "Idea de Negocio a la que pertenece")]
        public int IdeaDeNegocioID { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        public string Identificacion { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        public string Apellido { get; set; }
        [Required(ErrorMessage = "Campo requerido.")]
        public string Rol { get; set; }
        [EmailAddress(ErrorMessage = "Ingresa una dirección de correo electrónico válida.")]
        [Required(ErrorMessage = "Campo requerido.")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Campo requerido.")]
        [Display(Name = "Idea de Negocio a la que pertenece")]
        public virtual IdeaDeNegocio IdeaDeNegocio { get; set; }
    }
}
