//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAula4_SantiagoVieira_JohnSebastianVillegas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProyectoDeAula4JohnSebastian_SantiagoEntities : DbContext
    {
        public ProyectoDeAula4JohnSebastian_SantiagoEntities()
            : base("name=ProyectoDeAula4JohnSebastian_SantiagoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Herramienta4RI> Herramienta4RI { get; set; }
        public virtual DbSet<IdeaDeNegocio> IdeaDeNegocio { get; set; }
        public virtual DbSet<IntegranteEquipo> IntegranteEquipo { get; set; }
    }
}
